/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnativehook_GlobalScreen_NativeHookThread */

#ifndef _Included_org_jnativehook_GlobalScreen_NativeHookThread
#define _Included_org_jnativehook_GlobalScreen_NativeHookThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnativehook_GlobalScreen_NativeHookThread_MIN_PRIORITY
#define org_jnativehook_GlobalScreen_NativeHookThread_MIN_PRIORITY 1L
#undef org_jnativehook_GlobalScreen_NativeHookThread_NORM_PRIORITY
#define org_jnativehook_GlobalScreen_NativeHookThread_NORM_PRIORITY 5L
#undef org_jnativehook_GlobalScreen_NativeHookThread_MAX_PRIORITY
#define org_jnativehook_GlobalScreen_NativeHookThread_MAX_PRIORITY 10L
/*
 * Class:     org_jnativehook_GlobalScreen_NativeHookThread
 * Method:    enable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativehook_GlobalScreen_00024NativeHookThread_enable
  (JNIEnv *, jobject);

/*
 * Class:     org_jnativehook_GlobalScreen_NativeHookThread
 * Method:    disable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnativehook_GlobalScreen_00024NativeHookThread_disable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
