/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnativehook_GlobalScreen_EventDispatchTask */

#ifndef _Included_org_jnativehook_GlobalScreen_EventDispatchTask
#define _Included_org_jnativehook_GlobalScreen_EventDispatchTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
